name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'

      - run: npm ci

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 12.1
          postgresql db: node_test
          postgresql user: test
          postgresql password: test1123
          
      - run: npm run compile
      - run: npm run migration:run
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USERNAME: test
          POSTGRES_PASSWORD: test1123
          NODE_ENV: test

      - name: Run Specs
        run: npm test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USERNAME: test
          POSTGRES_PASSWORD: test1123
          NODE_ENV: test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: curl -X POST https://hooks.cloud66.com/stacks/redeploy/7b7bedb98c1d7e0983be4b6a69dfdc37/4df8eca2eaaa34102f7d0ce17dba30b5?services=web,worker
